version: '3.7'

services:

  archive:
    image: plotnikovas/archive:latest
    container_name: archive
    environment:
      DB_URL: jdbc:postgresql://timescale-archive:5432/archive
      DB_USER: local
      DB_PWD: local
      MINIO_URL: http://minio-archive:9000
      MINIO_USER: minio
      MINIO_PWD: minio123
    ports:
      - "8080:8080"
    networks:
      - local-network

  timescale-archive:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale-archive
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: archive
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    networks:
      - local-network

  minio-archive:
    image: minio/minio
    container_name: minio-archive
    restart: always
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    # Allow all incoming hosts to access the server by using 0.0.0.0
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - local-network

networks:
  local-network: